version: 2
updates:
  - package-ecosystem: maven
    directory: "/authentication-server"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10

 - package-ecosystem: maven
    directory: "/eureka-server"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
 
 - package-ecosystem: maven
    directory: "/first-service"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10

- package-ecosystem: maven
    directory: "/second-service"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10

- package-ecosystem: maven
    directory: "/gateway-server"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
